# Generated by Django 4.0.2 on 2022-02-05 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='key',
            name='is_available',
        ),
        migrations.DeleteModel(
            name='AuthorizationKey',
        ),
    ]
