# Generated by Django 4.0.1 on 2022-02-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='key',
            name='allow_heartrate_intraday_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='key',
            name='allow_heartrate_time_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='key',
            name='allow_sleep_time_series',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='key',
            name='allow_step_intraday_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='key',
            name='allow_step_time_series',
            field=models.BooleanField(default=False),
        ),
    ]
