# Generated by Django 4.0.1 on 2022-02-04 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0002_key_allow_heartrate_intraday_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorization_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('key', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualize.key')),
            ],
            options={
                'ordering': ['key', '-created_at'],
            },
        ),
    ]
