# Generated by Django 4.0.1 on 2022-02-04 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualize', '0004_key_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authorizationkey',
            name='expired_at',
        ),
    ]
