# Generated by Django 4.0.1 on 2022-01-31 01:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStepTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_uuid', models.CharField(max_length=100)),
                ('date_time', models.DateField()),
                ('steps', models.PositiveIntegerField()),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'date_time'],
            },
        ),
        migrations.CreateModel(
            name='UserStepIntradayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.JSONField(default=dict)),
                ('dataset_interval', models.PositiveSmallIntegerField()),
                ('dataset_type', models.CharField(max_length=100)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('time_series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.usersteptimeseries')),
            ],
            options={
                'ordering': ['time_series'],
            },
        ),
        migrations.CreateModel(
            name='UserSleepTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_uuid', models.CharField(max_length=100)),
                ('date_time', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('efficiency', models.PositiveSmallIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('minutes_after_wakeup', models.PositiveIntegerField()),
                ('minutes_asleep', models.PositiveIntegerField()),
                ('minutes_awake', models.PositiveIntegerField()),
                ('minutes_to_fall_asleep', models.PositiveIntegerField()),
                ('time_in_bed', models.PositiveIntegerField()),
                ('levels', models.JSONField(default=dict)),
                ('summary', models.JSONField(default=dict)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'date_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.JSONField(default=dict)),
                ('user_account_id', models.CharField(default='', max_length=100)),
                ('scope', models.JSONField(default=dict)),
                ('state_id', models.CharField(max_length=30)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserHeartRateTimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time_uuid', models.CharField(max_length=100)),
                ('date_time', models.DateField()),
                ('resting_heart_rate', models.PositiveSmallIntegerField()),
                ('heart_rate_zones', models.JSONField(default=dict)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'date_time'],
            },
        ),
        migrations.CreateModel(
            name='UserHeartRateIntradayData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.JSONField(default=dict)),
                ('dataset_interval', models.PositiveSmallIntegerField()),
                ('dataset_type', models.CharField(max_length=100)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('time_series', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.userheartratetimeseries')),
            ],
            options={
                'ordering': ['time_series'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devices', models.JSONField(default=dict)),
                ('last_sync_time', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', '-created_at'],
            },
        ),
    ]
