# Generated by Django 4.0.2 on 2022-02-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userheartratetimeseries',
            old_name='date_time_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='usersleeptimeseries',
            old_name='date_time_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='usersteptimeseries',
            old_name='date_time_uuid',
            new_name='uuid',
        ),
        migrations.RenameField(
            model_name='usersyncstatus',
            old_name='date_time_uuid',
            new_name='uuid',
        ),
    ]
