# Generated by Django 4.0.1 on 2022-02-03 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSyncStatus',
            fields=[
                ('date_time_uuid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('date_time', models.DateField()),
                ('heartrate_intraday_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.userheartrateintradaydata')),
                ('heartrate_time_series', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.userheartratetimeseries')),
                ('sleep_time_series', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.usersleeptimeseries')),
                ('step_intraday_data', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.userstepintradaydata')),
                ('step_time_series', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracker.usersteptimeseries')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.userprofile')),
            ],
            options={
                'ordering': ['user_profile', 'date_time'],
            },
        ),
    ]
