# Generated by Django 4.0.2 on 2022-02-04 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_usersyncstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_retrieving',
            field=models.BooleanField(default=False),
        ),
    ]
