# Generated by Django 4.0.1 on 2022-01-30 21:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker', '0006_rename_usersynchronizationstatus_userdevices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDevices',
            new_name='UserDevice',
        ),
    ]
