# Generated by Django 4.0.1 on 2022-01-30 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_rename_userdevices_userdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='scope',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_account_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
